# Generated by Django 2.2.4 on 2019-10-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsystems', '0007_component_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(help_text='The unique name of a usable component.', max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(fields=('agent_id', 'agent_service'), name='Agent Service Agent ID'),
        ),
    ]
