# Generated by Django 2.2.4 on 2019-10-27 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('siteapp', '0034_auto_20191027_0223'),
        ('itsystems', '0008_auto_20191027_0156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemInstance',
            new_name='System',
        ),
        migrations.RemoveField(
            model_name='hostinstance',
            name='system_instance',
        ),
        migrations.AddField(
            model_name='hostinstance',
            name='system',
            field=models.ForeignKey(blank=True, help_text='The System to which this HostInstance belongs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostinstances', to='itsystems.System'),
        ),
    ]
