# Generated by Django 2.2.4 on 2019-10-27 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itsystems', '0009_auto_20191027_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this Host Instance (e.g., workload/endpoint/server).', max_length=255, unique=True)),
                ('host_type', models.CharField(blank=True, help_text='A categorization of the host.', max_length=24, null=True)),
                ('os', models.CharField(blank=True, help_text='The Operating System running on the Host Instance.', max_length=155, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('system', models.ForeignKey(blank=True, help_text='The System to which this Host belongs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosts', to='itsystems.System')),
            ],
        ),
        migrations.RemoveField(
            model_name='agent',
            name='host_instance',
        ),
        migrations.DeleteModel(
            name='HostInstance',
        ),
        migrations.AddField(
            model_name='agent',
            name='host',
            field=models.ForeignKey(blank=True, help_text='The Host on which the Agent is installed and monitoring.', null=True, on_delete='models.SET_NULL', related_name='agents', to='itsystems.Host'),
        ),
    ]
