# Generated by Django 2.0.13 on 2019-07-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0027_auto_20190627_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'permissions': (('view_portfolio', 'View portfolio'), ('can_grant_portfolio_owner_permission', 'Grant a user portfolio owner permission'))},
        ),
    ]
