# Generated by Django 2.2.4 on 2019-10-27 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0033_project_systeminstance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='systeminstance',
            new_name='system',
        ),
    ]
